spring.application.name=FoodieBackend

# ===== SERVER =====
server.port=${PORT:8080}

# ===== DATABASE (POSTGRES) =====
spring.datasource.url=jdbc:postgresql://localhost:5432/foodie
spring.datasource.username=postgres
spring.datasource.password=postgres

app.cors.allowed-origins=http://localhost:5173,http://localhost:3000


spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
 
# ===== JWT =====
jwt.secret=${JWT_SECRET}

jwt.expiration=86400000

# ===== RAZORPAY =====
razorpay.key.id=${RAZORPAY_KEY: rzp_test_Sd3N6HaAMOsi0B}
razorpay.key.secret=${RAZORPAY_SECRET: k56MVWtzHKa8ZxCsjYU159kJ}

# ===== CORS =====
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000

# ===== FILE UPLOAD =====
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ===== LOGGING =====
logging.level.com.fodie=DEBUG
logging.level.org.springframework.security=WARN