spring.application.name=FoodieBackend

# ===== SERVER =====
server.port=${PORT:8080}

# ===== DATABASE (POSTGRES) =====
spring.datasource.url=jdbc:postgresql://dpg-d7q37j1kh4rs73aumsfg-a/foodie_abvl
spring.datasource.username=foodie_abvl_user
spring.datasource.password=VnoZlbRA0AeS0LUse6UWujAV9N8ksWww
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
 
# ===== JWT =====
jwt.secret=${JWT_SECRET}

jwt.expiration=86400000

# ===== RAZORPAY =====
razorpay.key.id=${RAZORPAY_KEY}
razorpay.key.secret=${RAZORPAY_SECRET}

# ===== CORS =====
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173

# ===== FILE UPLOAD =====
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ===== LOGGING =====
logging.level.com.fodie=DEBUG
logging.level.org.springframework.security=WARN